name: CI
on: workflow_dispatch
env:
 GH_TKN: ${{ secrets.gh }}
jobs:
  build:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3

      - name: Updating Secrets to repos
        env:
          json: ${{ secrets.json }}
        run: |
           sh key.sh
