name: Fetch value
on: [workflow_dispatch]
jobs:
 fetch_value:
  name: fetch job
  runs-on: Linux
  steps:
  - name: fetching values
    run: |
     > test.txt
     echo "${{ secrets.id}}" >> test.txt
     echo "${{ secrets.name }}" >> test.txt
     echo "${{ secrets.price }}" >> test.txt
     echo "${{ secrets.quantity }}" >> test.txt
     echo "${{ secrets.description }}" >> test.txt
     echo "${{ secrets.EMAIL }}" >> test.txt
     echo "${{ secrets.FRUIT }}" >> test.txt
     echo "${{ secrets.NAME }}" >> test.txt
     echo "${{ secrets.PUT }}" >> test.txt
     echo "${{ secrets.TEST }}" >> test.txt
